backend:
  name: github
  repo: pkeshi-s-castle/toidel-website
  branch: main
  base_url: https://toidel-website.pages.dev
  auth_endpoint: api/auth

media_folder: static/images/products
public_folder: /images/products

site_url: https://toidel-website.pages.dev
display_url: https://toidel-website.pages.dev

collections:
  - name: products
    label: Products
    label_singular: Product
    folder: content/products
    create: true
    delete: true
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    summary: "{{name}}"
    editor:
      preview: false
    fields:
      - { label: "Name", name: "name", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "markdown", required: false }
      - { label: "Picture", name: "picture", widget: "image", required: true }
